apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-3
  namespace: service-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-3
  template:
    metadata:
      labels:
        app: service-3
    spec:
      automountServiceAccountToken: false
      serviceAccountName: service-3
      containers:
        - name: httpbin
          image: kennethreitz/httpbin:latest
          ports:
            - containerPort: 80
