apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/istio
  - ../base/monitoring
  - ../base/keda
patches:
  - path: istio-patch.yaml
  - path: prometheus-clusterrole-patch.yaml
