apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-service-1-only
  namespace: service-2
spec:
  selector:
    matchLabels:
      app: service-2
  action: ALLOW
  rules:
  - {}
