apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1
  namespace: service-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-1
  template:
    metadata:
      labels:
        app: service-1
    spec:
      automountServiceAccountToken: false
      serviceAccountName: service-1
      containers:
        - name: httpbin
          image: kennethreitz/httpbin:latest
          ports:
            - containerPort: 80
